# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(750, 480))
        Form.setMaximumSize(QtCore.QSize(750, 480))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 420, 701, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.LB_cmd = QtWidgets.QLabel(self.widget)
        self.LB_cmd.setGeometry(QtCore.QRect(60, 5, 631, 31))
        self.LB_cmd.setText("")
        self.LB_cmd.setObjectName("LB_cmd")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 54, 21))
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(20, 20, 301, 391))
        self.widget_2.setObjectName("widget_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 281, 131))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.RB_Group3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RB_Group3.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RB_Group3.setFont(font)
        self.RB_Group3.setObjectName("RB_Group3")
        self.gridLayout_2.addWidget(self.RB_Group3, 1, 1, 1, 1)
        self.RB_Group6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RB_Group6.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RB_Group6.setFont(font)
        self.RB_Group6.setObjectName("RB_Group6")
        self.gridLayout_2.addWidget(self.RB_Group6, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.RB_Group1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RB_Group1.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RB_Group1.setFont(font)
        self.RB_Group1.setChecked(True)
        self.RB_Group1.setObjectName("RB_Group1")
        self.gridLayout_2.addWidget(self.RB_Group1, 0, 1, 1, 1)
        self.RB_Group4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RB_Group4.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RB_Group4.setFont(font)
        self.RB_Group4.setObjectName("RB_Group4")
        self.gridLayout_2.addWidget(self.RB_Group4, 1, 3, 1, 1)
        self.RB_Group2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RB_Group2.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RB_Group2.setFont(font)
        self.RB_Group2.setObjectName("RB_Group2")
        self.gridLayout_2.addWidget(self.RB_Group2, 0, 3, 1, 1)
        self.RB_Group5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RB_Group5.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RB_Group5.setFont(font)
        self.RB_Group5.setObjectName("RB_Group5")
        self.gridLayout_2.addWidget(self.RB_Group5, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 281, 231))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setGeometry(QtCore.QRect(10, 20, 251, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LB_V = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LB_V.setFont(font)
        self.LB_V.setObjectName("LB_V")
        self.gridLayout_3.addWidget(self.LB_V, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.LB_XY = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LB_XY.setFont(font)
        self.LB_XY.setObjectName("LB_XY")
        self.gridLayout_3.addWidget(self.LB_XY, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 3, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 251, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CB_positive = QtWidgets.QCheckBox(self.frame_2)
        self.CB_positive.setEnabled(False)
        self.CB_positive.setObjectName("CB_positive")
        self.horizontalLayout.addWidget(self.CB_positive)
        self.CB_zero = QtWidgets.QCheckBox(self.frame_2)
        self.CB_zero.setEnabled(False)
        self.CB_zero.setObjectName("CB_zero")
        self.horizontalLayout.addWidget(self.CB_zero)
        self.CB_negitive = QtWidgets.QCheckBox(self.frame_2)
        self.CB_negitive.setEnabled(False)
        self.CB_negitive.setObjectName("CB_negitive")
        self.horizontalLayout.addWidget(self.CB_negitive)
        self.CB_in4 = QtWidgets.QCheckBox(self.frame_2)
        self.CB_in4.setEnabled(False)
        self.CB_in4.setObjectName("CB_in4")
        self.horizontalLayout.addWidget(self.CB_in4)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_3.setGeometry(QtCore.QRect(10, 160, 251, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CB_O1 = QtWidgets.QCheckBox(self.frame_3)
        self.CB_O1.setObjectName("CB_O1")
        self.horizontalLayout_2.addWidget(self.CB_O1)
        self.CB_O2 = QtWidgets.QCheckBox(self.frame_3)
        self.CB_O2.setObjectName("CB_O2")
        self.horizontalLayout_2.addWidget(self.CB_O2)
        self.CB_buzzer = QtWidgets.QCheckBox(self.frame_3)
        self.CB_buzzer.setObjectName("CB_buzzer")
        self.horizontalLayout_2.addWidget(self.CB_buzzer)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(340, 20, 381, 391))
        self.widget_3.setObjectName("widget_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 361, 371))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        self.widget_4.setGeometry(QtCore.QRect(10, 20, 251, 331))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.PB_minus = QtWidgets.QPushButton(self.widget_4)
        self.PB_minus.setObjectName("PB_minus")
        self.gridLayout.addWidget(self.PB_minus, 7, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 8, 1, 1, 1)
        self.PB_runINC = QtWidgets.QPushButton(self.widget_4)
        self.PB_runINC.setObjectName("PB_runINC")
        self.gridLayout.addWidget(self.PB_runINC, 3, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 4, 1, 1, 1)
        self.PB_clear = QtWidgets.QPushButton(self.widget_4)
        self.PB_clear.setObjectName("PB_clear")
        self.gridLayout.addWidget(self.PB_clear, 7, 0, 1, 1)
        self.LE_ABS = QtWidgets.QLineEdit(self.widget_4)
        self.LE_ABS.setObjectName("LE_ABS")
        self.gridLayout.addWidget(self.LE_ABS, 1, 1, 1, 1)
        self.PB_pause = QtWidgets.QPushButton(self.widget_4)
        self.PB_pause.setObjectName("PB_pause")
        self.gridLayout.addWidget(self.PB_pause, 5, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 1, 1, 1)
        self.LE_INC = QtWidgets.QLineEdit(self.widget_4)
        self.LE_INC.setObjectName("LE_INC")
        self.gridLayout.addWidget(self.LE_INC, 3, 1, 1, 1)
        self.PB_runABS = QtWidgets.QPushButton(self.widget_4)
        self.PB_runABS.setObjectName("PB_runABS")
        self.gridLayout.addWidget(self.PB_runABS, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.PB_plus = QtWidgets.QPushButton(self.widget_4)
        self.PB_plus.setObjectName("PB_plus")
        self.gridLayout.addWidget(self.PB_plus, 7, 1, 1, 1)
        self.PB_neg = QtWidgets.QPushButton(self.widget_4)
        self.PB_neg.setObjectName("PB_neg")
        self.gridLayout.addWidget(self.PB_neg, 5, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 2, 1, 1, 1)
        self.PB_pos = QtWidgets.QPushButton(self.widget_4)
        self.PB_pos.setObjectName("PB_pos")
        self.gridLayout.addWidget(self.PB_pos, 5, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 6, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.groupBox)
        self.widget_5.setGeometry(QtCore.QRect(270, 20, 71, 331))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LCD = QtWidgets.QLCDNumber(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.LCD.setFont(font)
        self.LCD.setStyleSheet("color: rgb(85, 255, 0);\n"
"color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.LCD.setProperty("value", 20000.0)
        self.LCD.setObjectName("LCD")
        self.verticalLayout.addWidget(self.LCD, 0, QtCore.Qt.AlignHCenter)
        self.VSLIDER = QtWidgets.QSlider(self.widget_5)
        self.VSLIDER.setMinimum(400)
        self.VSLIDER.setMaximum(50000)
        self.VSLIDER.setProperty("value", 20000)
        self.VSLIDER.setOrientation(QtCore.Qt.Vertical)
        self.VSLIDER.setObjectName("VSLIDER")
        self.verticalLayout.addWidget(self.VSLIDER, 0, QtCore.Qt.AlignHCenter)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "智能步进电机控制器终端"))
        self.label_5.setText(_translate("Form", "指令："))
        self.groupBox_2.setTitle(_translate("Form", "电机组"))
        self.RB_Group3.setText(_translate("Form", "电机组3"))
        self.RB_Group6.setText(_translate("Form", "电机组6"))
        self.RB_Group1.setText(_translate("Form", "电机组1"))
        self.RB_Group4.setText(_translate("Form", "电机组4"))
        self.RB_Group2.setText(_translate("Form", "电机组2"))
        self.RB_Group5.setText(_translate("Form", "电机组5"))
        self.groupBox_3.setTitle(_translate("Form", "运行状态（复位）"))
        self.LB_V.setText(_translate("Form", "19790"))
        self.label_6.setText(_translate("Form", "坐标："))
        self.LB_XY.setText(_translate("Form", "19790"))
        self.label_8.setText(_translate("Form", "速度："))
        self.CB_positive.setText(_translate("Form", "正限"))
        self.CB_zero.setText(_translate("Form", "零点"))
        self.CB_negitive.setText(_translate("Form", "负限"))
        self.CB_in4.setText(_translate("Form", "入四"))
        self.CB_O1.setText(_translate("Form", "输出1"))
        self.CB_O2.setText(_translate("Form", "输出2"))
        self.CB_buzzer.setText(_translate("Form", "蜂鸣器"))
        self.groupBox.setTitle(_translate("Form", "操作"))
        self.label.setText(_translate("Form", "绝对："))
        self.PB_minus.setText(_translate("Form", "机械-"))
        self.PB_runINC.setText(_translate("Form", "运行"))
        self.PB_clear.setText(_translate("Form", "程序零"))
        self.LE_ABS.setText(_translate("Form", "10000"))
        self.PB_pause.setText(_translate("Form", "停止"))
        self.LE_INC.setText(_translate("Form", "1234"))
        self.PB_runABS.setText(_translate("Form", "运行"))
        self.label_2.setText(_translate("Form", "增量"))
        self.PB_plus.setText(_translate("Form", "机械+"))
        self.PB_neg.setText(_translate("Form", "反转"))
        self.PB_pos.setText(_translate("Form", "正转"))
